{% set name = "zig" %}
{% set version = "0.13.0" %}
{% set llvm_version = "18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ziglang/zig/archive/refs/tags/{{ version }}.tar.gz
    sha256: d3912858003e340f315224bf177d0f441d86b81f62854f5c141b6d51ab6b5516
    patches:
      - patches/0001-cross-findllvm.patch  # [linux and aarch64]
      # May be combined into a single patch once the build is found robust (few versions of zig)
      - patches/0001-win-set-MD-CMakeLists.txt.patch  # [win]
      - patches/0002-win-deprecations.patch  # [win]
      - patches/0003-win-LLVM_LIBRARIES-CMakeLists.txt.patch  # [win]
      - patches/0004-win-ZIG2_LINK_FLAGS-CMakeLists.txt.patch  # [win]
      - patches/0005-win-ZIG_BUILD_ARGS-CMakeLists.txt.patch  # [win]
      - patches/0006-win-add-libdir-build.zig.patch  # [win]
    folder: zig-source

  # We may need to use the upstream binary dist if conda ZIG cannot build a newer version
  # The zig variable in the build scripts would then need to be updated
  #
  # - folder: zig-bootstrap
  #   url: https://ziglang.org/download/{{ version }}/zig-windows-x86_64-{{ version }}.zip  # [win]
  #   sha256: d859994725ef9402381e557c60bb57497215682e355204d754ee3df75ee3c158  # [win]
  #   url: https://ziglang.org/download/{{ version }}/zig-macos-x86_64-{{ version }}.tar.xz  # [osx]
  #   sha256: 8b06ed1091b2269b700b3b07f8e3be3b833000841bae5aa6a09b1a8b4773effd  # [osx]
  #   url: https://ziglang.org/download/{{ version }}/zig-linux-x86_64-{{ version }}.tar.xz  # [linux]
  #   sha256: d45312e61ebcc48032b77bc4cf7fd6915c11fa16e4aad116b66c9468211230ea  # [linux]

build:
  number: 4
  script_env:
    - BUILD_WITH_CMAKE=1  # [(linux or osx or win) and x86_64]
  ignore_run_exports:
    - __glibc  # [linux and aarch64]
    - ucrt  # [win]
    - vc14_runtime  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ c_stdlib }}_{{ build_platform }} >={{ c_stdlib_version }}  # [linux and (aarch64 or ppc64le)]
    - {{ stdlib("c") }}
    - cmake >=3.5
    - ninja
    - zig  # [build_platform != target_platform]
  host:
    - clangdev {{ llvm_version }}
    - libclang-cpp {{ llvm_version }}
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - llvmdev {{ llvm_version }}
    - llvm {{ llvm_version }}
    - lld {{ llvm_version }}
    - sysroot_{{ target_platform }} >=2.28  # [linux and (aarch64 or ppc64le)]
    - libxml2  # [win]
    - zlib
    - zstd
  run:
    - sysroot_{{ target_platform }} >=2.28  # [linux and (aarch64 or ppc64le)]

test:
  commands:
    - test -f ${PREFIX}/bin/zig  # [unix]
    - test -f ${PREFIX}/lib/zig/c.zig  # [unix]
    - test -f ${PREFIX}/lib/zig/compiler_rt.zig  # [unix]
    - test -f ${PREFIX}/lib/zig/zig.h  # [unix]
    - if not exist %PREFIX%\\bin\\zig.exe exit 1  # [win]
    - if not exist %PREFIX%\\lib\\zig\\c.zig exit 1  # [win]
    - if not exist %PREFIX%\\lib\\zig\\compiler_rt.zig exit 1  # [win]
    - if not exist %PREFIX%\\lib\\zig\\zig.h exit 1  # [win]
    {% set lib_dirs = [
      "compiler", "compiler_rt", "docs", "include", "init", "libc",
      "libcxx", "libcxxabi", "libunwind", "std", "tsan"
    ] %}
    {% for lib_dir in lib_dirs %}
    - test -d ${PREFIX}/lib/zig/{{ lib_dir }}  # [not (osx and arm64 or win)]
    - if not exist %PREFIX%\\lib\\zig\\{{ lib_dir }} exit 1  # [win]
    {% endfor %}

    # Functionality tests
    - zig version
    - zig zen
    - zig init
    - zig test zig-source/test/behavior.zig  # [not win]
    # One test fails on windows: 838/1932 behavior.floatop.test.@log2 with vectors...FAIL (TestUnexpectedResult)
    - zig test zig-source/test/behavior.zig || true  # [win]
  source_files:
    - zig-source/test

about:
  home: https://ziglang.org/
  license: MIT
  license_family: MIT
  license_file: zig-source/LICENSE
  summary: Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
  description: |
    Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
    Robust: Behavior is correct even for edge cases such as out of memory.
    Optimal: Write programs the best way they can behave and perform.
    Reusable: The same code works in many environments which have different constraints.
    Maintainable: Precisely communicate intent to the compiler and other programmers. 
      The language imposes a low overhead to reading code and is resilient to changing requirements and environments.
  doc_url: https://ziglang.org/documentation/{{ version }}/
  dev_url: https://github.com/ziglang/zig

extra:
  recipe-maintainers:
    - MementoRC
    - xmnlab
