schema_version: 1

context:
  name: zig
  version: 0.15.2
  llvm_version: "20"
  llvm_src_version: "20.1.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/ziglang/zig/archive/refs/tags/${{ version }}.tar.gz
    sha256: ebe6eb7006f6bbb72e54bd25d0675f2794084909d63a95aa315f2dcf2af5fd99
    patches:
      - if: linux
        then:
          - patches/0001-x86-maxrss-CMakeLists.txt.patch
      - if: aarch64 or ppc64le
        then:
          - patches/0001-cross-findllvm.patch
          # Only apply other CMakeLists.txt patches when cross-compiling with CMake/QEMU (not needed with zig)
      - if: linux and (x86_64 or ppc64le)
        then:
          # Phase 0001: Architecture Support (add PowerPC64LE to CPU arch switches)
          - patches/0001-ppc64le-arch-support-relocation.zig.patch
          - patches/0001-ppc64le-arch-support-LdScript.zig.patch
          - patches/0001-ppc64le-arch-support-Elf.zig.patch
          - patches/0001-ppc64le-arch-support-Atom.zig.patch
          - patches/0001-ppc64le-arch-support-LinkerDefined.zig.patch
          - patches/0001-ppc64le-arch-support-ZigObject.zig.patch
          - patches/0001-ppc64le-arch-support-synthetic_sections.zig.patch
          - patches/0001-ppc64le-arch-support-eh_frame.zig.patch
          - patches/0001-ppc64le-arch-support-Thunk.zig.patch
          - patches/0001-ppc64le-arch-support-st-other-visibility.patch
          # Phase 0002: Build Configuration (LLVM backend, library paths)
          - patches/0002-ppc64le-build-config-build.zig.patch
          # Phase 0003: Linker Redirection (force LLD path → external GCC)
          - patches/0003-ppc64le-linker-redirect-link.zig.patch
          - patches/0021-ppc64le-gcc-linker-bypass-poc.patch  # PROOF-OF-CONCEPT: Bypass strategy
          # Debug (remove before release)
          - patches/9999-DEBUG-thunks-diagnostic.patch
      - if: win
        then:
          # May be combined into a single patch once the build is found robust (few versions of zig)
          - patches/0001-win-deprecations.patch
          - patches/0002-win-libraries-CMakeLists.txt.patch
          - patches/0003-win-add-libdir-build.zig.patch
          - patches/0004-win-remove-ucrt-Lld.zig.patch
    target_directory: zig-source

  - if: ppc64le
    then:
      - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ llvm_src_version }}.tar.gz
        sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
        target_directory: lld-source

  # Bootstrap fallback: Use upstream binary dist if conda ZIG cannot build a newer version
  # The zig variable in the build scripts would then need to be updated
  # Uncomment the following sections to enable bootstrap binaries:
  #
  # - folder: zig-bootstrap
  #   if: win
  #   url: https://ziglang.org/download/${{ version }}/zig-windows-x86_64-${{ version }}.zip
  #   sha256: ...
  #
  # - folder: zig-bootstrap
  #   if: osx
  #   url: https://ziglang.org/download/${{ version }}/zig-macos-x86_64-${{ version }}.tar.xz
  #   sha256: ...
  #
  # - folder: zig-bootstrap
  #   if: linux
  #   url: https://ziglang.org/download/${{ version }}/zig-linux-x86_64-${{ version }}.tar.xz
  #   sha256: ...

build:
  number: 3
  skip:
    - not (ppc64le or (linux and x86_64))
  script:
    content:
      - if: unix
        then:
          - bash ${RECIPE_DIR}/build.sh
      - if: win
        then:
          # The bld.bat script handles Windows builds
          - call %RECIPE_DIR%\build.bat
    env:
      BUILD_WITH_CMAKE: ${{ "1" if (x86_64 and not linux) }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.5
    - ninja
    - if: arm64 or aarch64 or ppc64le or (linux and x86_64)
      then: zig ==0.15.2
    - if: aarch64 or ppc64le
      then: ${{ c_stdlib }}_${{ build_platform }} ==${{ c_stdlib_version }}
    - if: ppc64le
      then:
        - clangdev ${{ llvm_version }}.*
        - libclang-cpp ${{ llvm_version }}.*
        - lld ${{ llvm_version }}.*
        - llvm ${{ llvm_version }}.*
        - llvmdev ${{ llvm_version }}.*
        - libxml2-devel
        - zlib
        - zstd
    - if: (build_platform != target_platform) and osx
      then: libxml2-devel
    - if: unix
      then:
        - file
        - perl 5.32.*

  host:
    - if: aarch64 or ppc64le
      then:
        - ${{ compiler('cxx') }}
    - clangdev ${{ llvm_version }}.*
    - libclang-cpp ${{ llvm_version }}.*
    - if: osx
      then:
        - libcxx ${{ llvm_version }}.*
    - libxml2-devel
    - llvmdev ${{ llvm_version }}.*
    - llvm ${{ llvm_version }}.*
    - lld ${{ llvm_version }}.*
    - if: aarch64 or ppc64le
      then:
        - sysroot_${{ target_platform }} ==${{ c_stdlib_version }}
    - zlib
    - zstd

  run:
    - if: aarch64 or ppc64le
      then:
        - sysroot_${{ target_platform }} >=${{ c_stdlib_version }}

  ignore_run_exports:
    by_name:
      - if: win
        then:
          - ucrt
          - vc14_runtime

tests:
  # Package contents verification
  - package_contents:
      bin:
        - zig
      files:
        - lib/zig/c.zig
        - lib/zig/compiler_rt.zig
        - lib/zig/zig.h
        - if: not (osx and arm64)
          then:
            - lib/zig/compiler/**
            - lib/zig/compiler_rt/**
            - lib/zig/docs/**
            - lib/zig/include/**
            - lib/zig/init/**
            - lib/zig/libc/**
            - lib/zig/libcxx/**
            - lib/zig/libcxxabi/**
            - lib/zig/libunwind/**
            - lib/zig/std/**

  # Functional tests
  - requirements:
      run:
        - if: linux and aarch64
          then:
            - patchelf
        # - if: aarch64 or ppc64le
        #   then:
        #     - sysroot_${{ target_platform }} >=${{ c_stdlib_version }}

    files:
      source:
        - zig-source/test

    script:
      - zig version
      - zig zen
      - zig init

      - if: unix
        then:
          - zig test zig-source/test/behavior.zig
      # One test fails on windows: 838/1932 behavior.floatop.test.@log2 with vectors...FAIL (TestUnexpectedResult)
      - if: not unix
        then:
          - zig test zig-source/test/behavior.zig || true

about:
  homepage: https://ziglang.org/
  license: MIT
  license_file:
    - zig-source/LICENSE
    - if: ppc64le
      then: lld-source/lld/LICENSE.TXT
  summary: Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
  description: |
    Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
    Robust: Behavior is correct even for edge cases such as out of memory.
    Optimal: Write programs the best way they can behave and perform.
    Reusable: The same code works in many environments which have different constraints.
    Maintainable: Precisely communicate intent to the compiler and other programmers.
      The language imposes a low overhead to reading code and is resilient to changing requirements and environments.
  documentation: https://ziglang.org/documentation/${{ version }}/
  repository: https://github.com/ziglang/zig

extra:
  recipe-maintainers:
    - MementoRC
    - xmnlab
    - tdejager
