schema_version: 1

context:
  build_number: 8
  name: zig
  version: 0.15.2
  llvm_version: "20"
  llvm_src_version: "20.1.8"
  zig_build_mode: "bootstrap"

  # Targets that need zig-llvmdev (no conda-forge LLVM/GCC available)
  # For bootstrap mode, only exotic archs without GCC toolchain need this
  needs_zig_llvmdev: ${{ TG_ in ["linux-riscv64", "linux-s390x"] }}
  
  library: ${{ "Library/" if not unix }}
  m2: ${{ "m2-" if not unix }}
  sh: ${{ ".bat" if not unix else ".sh" }}

  # Zig target mapping (for zig -target flag, differs from GCC triplets)
  zig_target: >-
    ${{
      "x86_64-linux-gnu"            if TG_ == "linux-64"       else
      "aarch64-linux-gnu"           if TG_ == "linux-aarch64"  else
      "powerpc64le-linux-gnu"       if TG_ == "linux-ppc64le"  else
      "riscv64-linux-gnu"           if TG_ == "linux-riscv64"  else
      "s390x-linux-gnu"             if TG_ == "linux-s390x"    else
      "x86_64-macos-none"           if TG_ == "osx-64"         else
      "aarch64-macos-none"          if TG_ == "osx-arm64"      else
      "x86_64-windows-gnu"          if TG_ == "win-64"         else
      "aarch64-windows-gnu"         if TG_ == "win-arm64"      else
      "native"
    }}

  # Conda-style triplet for binary prefixes (e.g., x86_64-conda-linux-gnu-zig)
  target_triplet: >-
    ${{
      "x86_64-conda-linux-gnu"      if TG_ == "linux-64"       else
      "aarch64-conda-linux-gnu"     if TG_ == "linux-aarch64"  else
      "powerpc64le-conda-linux-gnu" if TG_ == "linux-ppc64le"  else
      "riscv64-conda-linux-gnu"     if TG_ == "linux-riscv64"  else
      "s390x-conda-linux-gnu"       if TG_ == "linux-s390x"    else
      "x86_64-apple-darwin13.4.0"   if TG_ == "osx-64"         else
      "arm64-apple-darwin20.0.0"    if TG_ == "osx-arm64"      else
      "x86_64-w64-mingw32"          if TG_ == "win-64"         else
      "aarch64-w64-mingw32"         if TG_ == "win-arm64"      else
      "unknown"
    }}

  # Build mode detection helpers
  # Which platform builds cross-compilers for each target
  cross_build_platform: >-
    ${{
      "linux-64" if TG_ in [
          "linux-64",
          "linux-aarch64",
          "linux-ppc64le",
          "linux-riscv64",
          "linux-s390x",
          "osx-arm64",
          "win-arm64"
       ]                                                      else
      "osx-64"   if TG_ in ["osx-64"]                         else
      "win-64"   if TG_ == "win-64"                           else
      target_platform
    }}
  is_native: ${{ TG_ == build_platform }}
  is_cross_compiler: ${{ (TG_ != target_platform) and (build_platform == cross_build_platform) }}
  is_cross_target: ${{ (TG_ == target_platform) and (build_platform != target_platform) }}

recipe:
  name: zig-package
  version: ${{ version }}

source:
  - url: https://github.com/ziglang/zig/archive/refs/tags/${{ version }}.tar.gz
    sha256: ebe6eb7006f6bbb72e54bd25d0675f2794084909d63a95aa315f2dcf2af5fd99
    patches:
      - if: linux
        then:
          - patches/0001-linux-maxrss-build.zig.patch
      - if: linux and (x86_64 or ppc64le)
        then:
          # Phase 0001: Architecture Support (add PowerPC64LE to CPU arch switches)
          - patches/0001-ppc64le-arch-support-relocation.zig.patch
          - patches/0001-ppc64le-arch-support-LdScript.zig.patch
          - patches/0001-ppc64le-arch-support-Elf.zig.patch
          - patches/0001-ppc64le-arch-support-Atom.zig.patch
          - patches/0001-ppc64le-arch-support-LinkerDefined.zig.patch
          - patches/0001-ppc64le-arch-support-ZigObject.zig.patch
          - patches/0001-ppc64le-arch-support-synthetic_sections.zig.patch
          - patches/0001-ppc64le-arch-support-eh_frame.zig.patch
          - patches/0001-ppc64le-arch-support-Thunk.zig.patch
          - patches/0001-ppc64le-arch-support-st-other-Object.zig.patch
          - patches/0001-ppc64le-arch-support-st-other-SharedObject.zig.patch
          # Phase 0002: Build Configuration (LLVM backend, library paths)
          - patches/0002-ppc64le-build-config-build.zig.patch
          # Phase 0003: Linker Redirection (comprehensive GCC linker with full flag translation)
          - patches/0003-ppc64le-linker-redirect-link.zig.patch
          - patches/0003-ppc64le-ldscript-output-format.patch
          - patches/0003-ppc64le-gcc-linker-comprehensive-Lld.zig.patch
      - if: not unix
        then:
          - patches/0001-win-maxrss-search-prefix-build.zig.patch
          - patches/0001-win-correct-LLVM_LIBRARIES-CMakeLists.txt.patch
          - patches/0001-win-remove-ucrt-Lld.zig.patch
          - patches/0002-win-MD-libzigcpp-CMakeLists.txt.patch
    target_directory: zig-source
  - if: ppc64le
    then:
      - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ llvm_src_version }}.tar.gz
        sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
        target_directory: lld-source
  # LLVM source for zig-llvmdev (targets without conda-forge LLVM)
  - if: needs_zig_llvmdev
    then:
      - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ llvm_src_version }}.tar.gz
        sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
        target_directory: llvm-source

build:
  number: ${{ build_number }}

outputs:
  # ==========================================================================
  # ZIG-LLVMDEV: LLVM built with zig cc (for targets without conda-forge LLVM)
  # Produces shared libraries with libc++ ABI compatible with zig-cc-built code
  # ==========================================================================
#  - package:
#      name: zig-llvmdev
#    build:
#      skip: not needs_zig_llvmdev
#      script:
#        file: build_llvmdev.sh
#        env:
#          ZIG_TARGET: ${{ zig_target }}
#    requirements:
#      build:
#        - ${{ m2 }}bash >=5.2
#        - cmake >=3.19
#        - ninja
#        - if: match(version, ">=0.15.2") and (build_number > 8)
#          then:
#            - zig_impl_${{ build_platform }} >=0.15.2
#      host:
#        - libxml2-devel
#        - zlib
#        - zstd
#    tests:
#      - package_contents:
#          files:
#            # Installed to lib/zig-llvm/ to avoid conflicts with conda-forge llvmdev
#            - lib/zig-llvm/lib/libLLVM*
#            - lib/zig-llvm/lib/libclang*
#            - lib/zig-llvm/lib/liblld*
#            - lib/zig-llvm/include/llvm/**
#            - lib/zig-llvm/include/clang/**
#            - lib/zig-llvm/include/lld/**
#            - lib/zig-llvm/bin/llvm-config
#            - lib/zig-llvm-path.txt

  # ==========================================================================
  # IMPLEMENTATION: zig_impl_$TG_ (binaries + stdlib ONLY)
  # Contains actual zig compiler binary (triplet-prefixed) and standard library
  # NO activation scripts, NO wrappers - just the implementation
  # ==========================================================================
  - package:
      name: zig_impl_${{ TG_ }}
    build:
      # Build zig_impl ONLY for native and cross-target (actual binary compilation)
      # Skip cross-compiler: uses native zig configured as cross-compiler, no new binary
      skip: needs_zig_llvmdev or not (is_native or is_cross_target)
      dynamic_linking:
        missing_dso_allowlist:
          - if: osx
            then: /usr/lib/libSystem.B.dylib
          - if: not unix
            then: "*/VERSION.dll"
      script:
        env:
          BUILD_NUMBER: ${{ build_number }}
          PKG_VARIANT: impl
          TARGET_TRIPLET: ${{ target_triplet }}
          ZIG_BUILD_MODE: ${{ zig_build_mode }}
          ZIG_TARGET: ${{ zig_target }}
    requirements:
      build:
        # --- Common build deps (all cases) ---
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - ${{ m2 }}bash >=5.2
        - ${{ m2 }}file
        - cmake >=3.5
        - ninja
        - perl 5.32.*

        - if: (build_platform != target_platform) and osx
          then:
            - libxml2-devel

        # --- BOOTSTRAP ZIG ---
        # Use zig_impl_$build_platform to break cycle (not zig metapackage)
        # For build_number <= 8: mamba workaround in build.sh
        # For build_number > 8: standard dependency on zig_impl_*
        # For needs_zig_llvmdev: mamba workaround in build.sh (zig-llvmdev handles its own bootstrap)
        - if: (is_native or is_cross_compiler) and (TG_ != build_platform) and not needs_zig_llvmdev
          then:
            - if: match(version, ">=0.15.2") and (build_number > 8)
              then:
                - zig_impl_${{ build_platform }} >=0.15.2

        # --- CROSS-TARGET: ppc64le-specific ---
        - if: is_cross_target and ppc64le
          then:
            # Needed to cross-compile ppc64le LLD with mcmodel=medium to prevent unsupported relocation
            - llvmdev ${{ llvm_version }}.*
      host:
        # LLVM dependencies: use zig-llvmdev for targets without conda-forge LLVM
        - if: needs_zig_llvmdev
          then:
            - zig-llvmdev
          else:
            - clangdev ${{ llvm_version }}.*
            - libclang-cpp ${{ llvm_version }}.*
            - llvm ${{ llvm_version }}.*
            - llvmdev ${{ llvm_version }}.*
            - lld ${{ llvm_version }}.*
        - libxml2-devel
        - zlib
        - zstd
        - if: (aarch64 or ppc64le) and not needs_zig_llvmdev
          then:
            - ${{ compiler('cxx') }}
        - if: osx
          then:
            - libcxx ${{ llvm_version }}.*
      run:
        - if: ppc64le
          then:
            # We redirect linking to gcc/ld.bfd
            - binutils_impl_${{ target_platform }} >=2.45
            - gcc_impl_${{ target_platform }} >=14.3
      ignore_run_exports:
        by_name:
          - if: win
            then:
              - ucrt
              - vc14_runtime
        from_package:
          - if: linux
            then:
              # Linux: zig doesn't directly link libxml2, it's transitive via libllvm20
              - libxml2-devel
          - if: osx and arm64
            then:
              - libclang-cpp
              - llvm
    tests:
      # Package contents verification - impl has triplet-prefixed binary
      - package_contents:
          strict: true
          bin:
            - ${{ target_triplet }}-zig
          files:
            - doc/langref.html
            - lib/zig/{c,compiler_rt,fuzzer,ubsan_rt}.zig
            - lib/zig/zig.h
            - lib/zig/build-web/*
            - lib/zig/c/{common,inttypes,stdlib,string,strings}.zig
            - lib/zig/compiler/**
            - lib/zig/compiler_rt/**
            - lib/zig/docs/**
            - lib/zig/include/**
            - lib/zig/init/**
            - lib/zig/libc/**
            - lib/zig/libcxx/**
            - lib/zig/libcxxabi/**
            - lib/zig/libunwind/**
            - lib/zig/libtsan/**
            - lib/zig/std/**
            # Post-install tests
            - etc/conda/test-files/zig*
      # Functional test using triplet-prefixed binary
      - script:
          - if: not arm64
            then:
              - ${{ target_triplet }}-zig version
              - ${{ target_triplet }}-zig zen
              - ${{ target_triplet }}-zig init
              - ${{ target_triplet }}-zig test zig-source/test/behavior.zig
            else:
              - echo "Skip test on arm64"
        files:
          source:
            - zig-source/test

  # ==========================================================================
  # ACTIVATION: zig_$TG_ (scripts + wrappers ONLY)
  # Contains activation scripts, wrapper scripts, depends on zig_impl_$TG_
  # NO binaries - just the environment setup
  # ==========================================================================
  - package:
      name: zig_${{ TG_ }}
    build:
      skip: not (is_native or is_cross_compiler or is_cross_target)
      # Not noarch - wrappers have platform-specific content
      script:
        file: install_zig_activation.py
        env:
          ZIG_TARGET: ${{ zig_target }}
          TARGET_TRIPLET: ${{ target_triplet }}
          TG_: ${{ TG_ }}
    requirements:
      build:
        - python 3.12.*
      # No host dep needed - install script just creates wrapper text, doesn't need impl binary
      run:
        # Cross-compiler needs NATIVE impl (runs on target_platform, produces code for TG_)
        # Uses previous build (bootstrapping cycle - can't use current build number)
        # Native/cross-target needs TG_ impl (same matrix entry, can pin)
        - if: is_cross_compiler
          then:
            - if: match(version, ">=0.15.2") and (build_number > 8)
              then:
                - zig_impl_${{ target_platform }} >=${{ version }}
          else:
            - ${{ pin_subpackage("zig_impl_" ~ TG_, exact=True) }}
    tests:
      - package_contents:
          strict: true
          bin:
            # Main wrapper only created for cross-compiler builds
            - if: is_cross_compiler
              then:
                - ${{ target_triplet }}-zig
            # Tool wrappers (all build types)
            - ${{ target_triplet }}-zig-cc
            - ${{ target_triplet }}-zig-c++
            - ${{ target_triplet }}-zig-ar
          files:
            - etc/conda/activate.d/zig_activate${{ sh }}
            - etc/conda/deactivate.d/zig_deactivate${{ sh }}
            # Post-install tests
            - etc/conda/test-files/zig_${{ TG_ }}/*
      # Comprehensive wrapper validation tests
      - script:
          - if: match(version, ">=0.15.2") and (build_number > 8)
            then:
              - if: not arm64
                then:
                  - ${{ target_triplet }}-zig version
                  - python testing/test_conda_zig_wrappers.py
                else:
                  - echo "Skip functional tests on arm64"
            else:
              - echo "Skip tests on build _8"
        requirements:
          run:
            - python >=3.10
        files:
          recipe:
            - testing/test_conda_zig_wrappers.py

  # ==========================================================================
  # METAPACKAGE: zig (native symlinks)
  # Creates unprefixed symlinks: zig -> $TRIPLET-zig
  # Only built when TG_ == target_platform
  # ==========================================================================
  - package:
      name: zig
    build:
      skip: TG_ != target_platform
      # Not noarch - creates symlinks (Unix) or wrappers (Windows) to platform-specific binaries
      script:
        file: install_zig_symlinks.py
        env:
          TARGET_TRIPLET: ${{ target_triplet }}
          TG_: ${{ TG_ }}
    requirements:
      build:
        - python 3.12.*
      host:
        # Host dep ensures targets exist during build for symlink validation
        - ${{ pin_subpackage("zig_" ~ TG_, exact=True) }}
      run:
        - ${{ pin_subpackage("zig_" ~ TG_, exact=True) }}
      run_exports:
        - ${{ pin_subpackage("zig", upper_bound="x.x.x") }}
    tests:
      - package_contents:
          strict: true
          bin:
            # Unprefixed symlinks to triplet-prefixed binaries
            - zig
            - zig-cc
            - zig-c++
            - zig-ar
            # NOTE: No conda-zig-* wrappers (unlike OCaml, zig doesn't bake paths)
      - script:
          - if: not arm64
            then:
              - zig version
            else:
              - echo "Skip on cross-compiled platform"

  # ==========================================================================
  # TOOLCHAIN META-PACKAGE: zig-compiler (toolchain metapackage)
  # Bundles zig with C toolchain for full development environment
  # ==========================================================================
  - package:
      name: zig-compiler
    build:
      noarch: generic
      # Only build when building native compiler
      skip: TG_ != target_platform
      script: echo "zig-compiler metapackage"
    requirements:
      run:
        - ${{ pin_subpackage("zig", exact=True) }}
        - c-compiler
        - if: linux
          then:
            - binutils_impl_${{ target_platform }}
        - if: osx
          then:
            - lld
            - llvm-tools
    tests:
      - script:
          - zig version
          - zig cc --version

about:
  homepage: https://ziglang.org/
  license: MIT
  license_file: zig-source/LICENSE
  summary: Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
  description: |
    Zig is a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
    Robust: Behavior is correct even for edge cases such as out of memory.
    Optimal: Write programs the best way they can behave and perform.
    Reusable: The same code works in many environments which have different constraints.
    Maintainable: Precisely communicate intent to the compiler and other programmers.
      The language imposes a low overhead to reading code and is resilient to changing requirements and environments.
  documentation: https://ziglang.org/documentation/${{ version }}/
  repository: https://github.com/ziglang/zig

extra:
  recipe-maintainers:
    - MementoRC
    - xmnlab
    - tdejager
  feedstock_name: zig
