os_version:
  linux_64: cos7
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
build_platform:
  linux_aarch64: linux_64
test: native_and_emulated
azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
