os_version:
  linux_64: cos7
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
  linux_ppc64le: linux_64
test: native_and_emulated
provider:
  linux_ppc64le: default
